## trace
level.color.TRACE.bold=false
level.color.TRACE=#008080
## debug
level.color.DEBUG.bold=false
level.color.DEBUG=#0070F5
## info
level.color.INFO.bold=false
level.color.INFO=#55B246
## warn
level.color.WARN.bold=false
level.color.WARN=#FF8E00
## error
level.color.ERROR.bold=true
level.color.ERROR=#B22234
